In [1]:
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn.model_selection import StratifiedShuffleSplit

data = pd.read_csv('data/Bank_Personal_Loan_Modelling.csv')
target_column = 'Personal Loan'

split = StratifiedShuffleSplit(n_splits=1, train_size=4000, test_size=1000, random_state=42)

for train_index, test_index in split.split(data, data[target_column]):
    train_data = data.iloc[train_index]
    test_data = data.iloc[test_index]

def random_date(start, end, n):
    delta = end - start
    random_days = np.random.randint(0, delta.days, size=n)
    return start + pd.to_timedelta(random_days, unit='D')

# Generate random dates (may to august)
start_train = datetime(2023, 5, 1)  
end_train = datetime(2023, 8, 31)   
train_data['Date'] = random_date(start_train, end_train, len(train_data))

# Generate random dates (september)
start_test = datetime(2023, 9, 1) 
end_test = datetime(2023, 9, 30)    
test_data['Date'] = random_date(start_test, end_test, len(test_data))

# #add new column with constant values 
# train_data['Constant column'] = 100
# test_data['Constant column'] = 100

# #add new random column√¨
# train_data['Random column'] = np.random.rand(len(train_data))
# test_data['Random column'] = np.random.rand(len(test_data))

train_data.to_csv('data/train_data.csv', index=False)
test_data.to_csv('data/test_data.csv', index=False)

# add Nans to Education
if 'Education' in train_data.columns:
    random_indices = np.random.choice(train_data.index, size=100, replace=False)
    train_data.loc[random_indices, 'Education'] = np.nan
    train_data.to_csv('data/train_data.csv', index=False)
    print("100 null values added to the 'Education' column and dataset saved.")
else:
    print("'Education' column not found in the dataset.")


print('Train Data:')
train = pd.read_csv("data/train_data.csv")
print(train['Personal Loan'].value_counts())
print(train.head())

print('Test Data:')
test = pd.read_csv("data/test_data.csv")
print(test['Personal Loan'].value_counts())
print(test.head())

100 null values added to the 'Education' column and dataset saved.
Train Data:
Personal Loan
0    3616
1     384
Name: count, dtype: int64
     ID  Age  Experience  Income  ZIP Code  Family CCAvg  Education  Mortgage  \
0   409   60          36      89     91745       2  2/80        1.0         0
1  3738   44          19      30     91423       1  0/50        3.0         0
2  3890   26           0      19     93014       1  0/10        2.0       121
3   569   34           9      41     92101       2  0/10        1.0       161
4  1042   56          32      51     92780       4  1/50        1.0         0

   Personal Loan  Securities Account  CD Account  Online  CreditCard  \
0              0                   0           0       1           0
1              0                   0           0       1           0
2              0                   0           0       1           0
3              0                   0           0       1           1
4              0                   0           0       0           0

         Date
0  2023-05-14
1  2023-05-03
2  2023-06-20
3  2023-08-15
4  2023-08-02
Test Data:
Personal Loan
0    904
1     96
Name: count, dtype: int64
     ID  Age  Experience  Income  ZIP Code  Family CCAvg  Education  Mortgage  \
0  2389   64          39      23     91768       3  0/50          1         0
1  2374   33           9     184     94304       2  4/80          2         0
2  4348   58          33      22     90024       3  0/20          1         0
3   666   54          24      61     92866       4  2/00          3         0
4  4183   55          29      49     92691       2  0/80          3       220

   Personal Loan  Securities Account  CD Account  Online  CreditCard  \
0              0                   1           0       0           0
1              1                   0           0       0           0
2              0                   0           0       1           0
3              0                   1           0       1           0
4              0                   0           0       0           1

         Date
0  2023-09-11
1  2023-09-25
2  2023-09-27
3  2023-09-06
4  2023-09-24

/var/folders/q8/7ss60v9d2t91mvvwbkcjcd3h0000gn/T/ipykernel_58789/686329822.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data['Date'] = random_date(start_train, end_train, len(train_data))
/var/folders/q8/7ss60v9d2t91mvvwbkcjcd3h0000gn/T/ipykernel_58789/686329822.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data['Date'] = random_date(start_test, end_test, len(test_data))

In [5]:
val_prep = pd.read_csv("data/test_data.csv")
val_prep.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard,Date
0,2389,64,39,23,91768,3,0/50,1,0,0,1,0,0,0,2023-09-11
1,2374,33,9,184,94304,2,4/80,2,0,1,0,0,0,0,2023-09-25
2,4348,58,33,22,90024,3,0/20,1,0,0,0,0,1,0,2023-09-27
3,666,54,24,61,92866,4,2/00,3,0,0,1,0,1,0,2023-09-06
4,4183,55,29,49,92691,2,0/80,3,220,0,0,0,0,1,2023-09-24